'use strict';
// Offline dictionary of common errors -> friendly explanations in 6 languages.
// Each rule: re (matched against the diagnostic message), then {en,ar,fr,de,ja,zh}.

const RULES = [
  { re: /cannot find name ['"`]?(\S+?)['"`]?(\.|$| )|(\S+) is not defined|name ['"`](\S+)['"`] is not defined|["“](\S+)["”] is not defined|undeclared identifier|was not declared in this scope|cannot find symbol/i,
    en: 'A name is used that the program does not know. Check the spelling (capital/small letters matter), or declare/import it before using it.',
    ar: 'تم استخدام اسم لا يعرفه البرنامج. راجع الإملاء (حالة الأحرف مهمة)، أو عرّفه/استورده قبل استخدامه.',
    fr: "Un nom est utilisé sans être connu du programme. Vérifiez l'orthographe (majuscules/minuscules) ou déclarez/importez-le avant de l'utiliser.",
    de: 'Es wird ein Name verwendet, den das Programm nicht kennt. Prüfen Sie die Schreibweise (Groß-/Kleinschreibung) oder deklarieren/importieren Sie ihn vorher.',
    ja: '未定義の名前が使われています。スペル（大文字・小文字）を確認するか、使う前に宣言・インポートしてください。',
    zh: '使用了程序不认识的名称。请检查拼写（区分大小写），或在使用前先声明/导入。' },
  { re: /(';'|"\;"|‘;’|semicolon) expected|expected ['"`]?;['"`]?|missing ['"`]?;['"`]?|expected ';'/i,
    en: 'A semicolon ( ; ) is missing, usually at the end of the line before this one.',
    ar: 'ينقص فاصلة منقوطة ( ; )، غالباً في نهاية السطر الذي قبل هذا السطر.',
    fr: 'Il manque un point-virgule ( ; ), souvent à la fin de la ligne précédente.',
    de: 'Es fehlt ein Semikolon ( ; ), meist am Ende der vorherigen Zeile.',
    ja: 'セミコロン（;）が不足しています。多くは直前の行の末尾です。',
    zh: '缺少分号（;），通常在上一行的末尾。' },
  { re: /['"`]?[)\]}]['"`]? expected|was not closed|expected ['"`]?[)\]}]['"`]?|unexpected end of input|unterminated|missing \)|expected closing|unclosed/i,
    en: 'A bracket or quote was opened but never closed. Count the ( [ { and quotes, and close the missing one.',
    ar: 'تم فتح قوس أو علامة اقتباس ولم يتم إغلاقها. عدّ الأقواس ( [ { وعلامات الاقتباس وأغلق الناقص.',
    fr: "Une parenthèse, un crochet ou un guillemet a été ouvert sans être fermé. Comptez-les et fermez celui qui manque.",
    de: 'Eine Klammer oder ein Anführungszeichen wurde geöffnet, aber nie geschlossen. Zählen Sie ( [ { und Anführungszeichen und schließen Sie das fehlende.',
    ja: '括弧または引用符が開いたまま閉じられていません。( [ { や引用符の数を数えて、足りないものを閉じてください。',
    zh: '括号或引号打开后没有关闭。请数一数 ( [ { 和引号，把缺少的补上。' },
  { re: /cannot find module|module not found|modulenotfounderror|no module named|import ["']?(\S+)["']? could not be resolved|cannot resolve|no such file or directory/i,
    en: 'The module or file cannot be found. Check the name/path, and install the package if it is external (for example: npm install name, or pip install name).',
    ar: 'لا يمكن العثور على الوحدة أو الملف. راجع الاسم/المسار، وثبّت الحزمة إن كانت خارجية (مثلاً: npm install الاسم أو pip install الاسم).',
    fr: "Le module ou fichier est introuvable. Vérifiez le nom/chemin et installez le paquet s'il est externe (par ex. npm install nom ou pip install nom).",
    de: 'Das Modul oder die Datei wurde nicht gefunden. Prüfen Sie Name/Pfad und installieren Sie externe Pakete (z. B. npm install name oder pip install name).',
    ja: 'モジュールまたはファイルが見つかりません。名前・パスを確認し、外部パッケージなら npm install 名前 / pip install 名前 でインストールしてください。',
    zh: '找不到模块或文件。请检查名称/路径；如果是外部包，请先安装（例如 npm install 名称 或 pip install 名称）。' },
  { re: /indentationerror|unexpected indent|unindent does not match|expected an indented block|inconsistent use of tabs/i,
    en: 'Python indentation problem. Lines in the same block must start with the same number of spaces. Do not mix Tab and spaces.',
    ar: 'مشكلة في المسافات البادئة في Python. أسطر نفس الكتلة يجب أن تبدأ بنفس عدد المسافات. لا تخلط بين Tab والمسافات.',
    fr: "Problème d'indentation Python. Les lignes d'un même bloc doivent commencer par le même nombre d'espaces. Ne mélangez pas Tab et espaces.",
    de: 'Python-Einrückungsfehler. Zeilen im selben Block müssen gleich viele Leerzeichen haben. Mischen Sie nicht Tab und Leerzeichen.',
    ja: 'Python のインデントの問題です。同じブロックの行は同じ数のスペースで始めてください。Tab とスペースを混ぜないでください。',
    zh: 'Python 缩进问题。同一代码块的行必须有相同数量的空格，不要混用 Tab 和空格。' },
  { re: /syntaxerror|invalid syntax|unexpected token|expression expected|expected expression|declaration or statement expected|unexpected character/i,
    en: 'Syntax error: the code is not written in a form the language understands. Look at this line and the one before it for a missing symbol or a typo.',
    ar: 'خطأ في الصياغة: الكود غير مكتوب بشكل تفهمه اللغة. افحص هذا السطر والسطر الذي قبله بحثاً عن رمز ناقص أو خطأ إملائي.',
    fr: "Erreur de syntaxe : le code n'est pas écrit sous une forme comprise par le langage. Regardez cette ligne et la précédente (symbole manquant ou faute de frappe).",
    de: 'Syntaxfehler: Der Code ist nicht in einer Form geschrieben, die die Sprache versteht. Prüfen Sie diese und die vorherige Zeile auf fehlende Symbole oder Tippfehler.',
    ja: '構文エラー：言語が理解できない書き方です。この行と前の行で、記号の不足やタイプミスがないか確認してください。',
    zh: '语法错误：代码的写法语言无法理解。请检查这一行和上一行是否缺少符号或有拼写错误。' },
  { re: /cannot read propert(y|ies)|of (undefined|null)|is not a function|is possibly ['"`]?(undefined|null)|object is possibly|nonetype|attributeerror/i,
    en: 'You are using a value that is empty (undefined/null/None) as if it had content. Check that the variable was given a value before using it.',
    ar: 'تستخدم قيمة فارغة (undefined/null/None) وكأن بها محتوى. تأكد أن المتغير أخذ قيمة قبل استخدامه.',
    fr: "Vous utilisez une valeur vide (undefined/null/None) comme si elle avait un contenu. Vérifiez que la variable a reçu une valeur avant de l'utiliser.",
    de: 'Sie verwenden einen leeren Wert (undefined/null/None), als hätte er Inhalt. Prüfen Sie, ob die Variable vorher einen Wert bekommen hat.',
    ja: '空の値（undefined/null/None）を中身があるかのように使っています。使う前に変数へ値が入っているか確認してください。',
    zh: '把空值（undefined/null/None）当成有内容的值在使用。请确认变量在使用前已被赋值。' },
  { re: /is not assignable to|incompatible types|type mismatch|typeerror|cannot convert|argument of type/i,
    en: 'The type of a value does not match what is expected (for example text where a number is required). Convert the value or fix the type.',
    ar: 'نوع القيمة لا يطابق المتوقع (مثلاً نص بدل رقم). حوّل القيمة أو صحّح النوع.',
    fr: "Le type d'une valeur ne correspond pas à celui attendu (par ex. du texte au lieu d'un nombre). Convertissez la valeur ou corrigez le type.",
    de: 'Der Typ eines Werts passt nicht zum erwarteten (z. B. Text statt Zahl). Wert umwandeln oder Typ korrigieren.',
    ja: '値の型が期待と一致しません（例：数値が必要なのに文字列）。値を変換するか型を修正してください。',
    zh: '值的类型与预期不符（例如需要数字却给了文本）。请转换该值或修正类型。' },
  { re: /does not exist on type|has no attribute|has no member|no member named|unknown property|is not a member/i,
    en: 'This property or method does not exist on that object. Check the spelling, or the object may be a different type than you think.',
    ar: 'هذه الخاصية أو الدالة غير موجودة في هذا الكائن. راجع الإملاء، أو قد يكون نوع الكائن مختلفاً عمّا تتوقع.',
    fr: "Cette propriété ou méthode n'existe pas sur cet objet. Vérifiez l'orthographe ; l'objet n'a peut-être pas le type attendu.",
    de: 'Diese Eigenschaft oder Methode existiert für dieses Objekt nicht. Prüfen Sie die Schreibweise; das Objekt hat evtl. einen anderen Typ.',
    ja: 'このオブジェクトにそのプロパティ／メソッドはありません。スペルを確認するか、オブジェクトの型が想定と違わないか確認してください。',
    zh: '该对象上不存在此属性或方法。请检查拼写，或确认对象的类型是否与你想的一致。' },
  { re: /declared but (its value is )?never (read|used)|is assigned a value but never used|unused (variable|import)|never used|is not accessed/i,
    en: 'This is only a hint: you created something but never used it. You can delete it or use it.',
    ar: 'مجرد تنبيه: أنشأت شيئاً ولم تستخدمه. يمكنك حذفه أو استخدامه.',
    fr: "Simple indication : vous avez créé quelque chose sans l'utiliser. Supprimez-le ou utilisez-le.",
    de: 'Nur ein Hinweis: Sie haben etwas angelegt, aber nie verwendet. Löschen oder verwenden Sie es.',
    ja: 'ヒントです：作成したものが使われていません。削除するか、使ってください。',
    zh: '这只是提示：你创建了某个东西却没有使用。可以删除它或加以使用。' },
  { re: /missing return|not all code paths return|function lacks ending return|control reaches end of non-void/i,
    en: 'The function should return a value on every path, but one path ends without a return.',
    ar: 'يجب أن تُرجع الدالة قيمة في كل المسارات، لكن هناك مسار ينتهي بدون return.',
    fr: "La fonction doit retourner une valeur sur tous les chemins, mais l'un d'eux se termine sans return.",
    de: 'Die Funktion sollte auf jedem Pfad einen Wert zurückgeben, aber ein Pfad endet ohne return.',
    ja: '関数はすべての経路で値を返す必要がありますが、return のない経路があります。',
    zh: '函数应在每条路径上都返回值，但有一条路径没有 return 就结束了。' },
  { re: /should be declared in a file named|public class .* is public/i,
    en: 'In Java, a public class must be inside a file with exactly the same name (for example Main → Main.java).',
    ar: 'في Java يجب أن يكون الصنف العام داخل ملف بنفس اسمه تماماً (مثلاً Main ← Main.java).',
    fr: 'En Java, une classe publique doit se trouver dans un fichier portant exactement son nom (ex. Main → Main.java).',
    de: 'In Java muss eine öffentliche Klasse in einer Datei mit genau demselben Namen stehen (z. B. Main → Main.java).',
    ja: 'Java では public クラスは同じ名前のファイルに置く必要があります（例：Main → Main.java）。',
    zh: '在 Java 中，public 类必须放在同名文件中（例如 Main → Main.java）。' },
  { re: /expected (a )?(comma|colon|property name|double-quoted)|trailing comma|colon expected|comma expected|property name expected|value expected/i,
    en: 'JSON problem: check commas between items (none after the last one), quotes around names ("name"), and colons.',
    ar: 'مشكلة في JSON: راجع الفواصل بين العناصر (بدون فاصلة بعد الأخير)، وعلامات الاقتباس حول الأسماء ("اسم")، والنقطتين.',
    fr: 'Problème JSON : vérifiez les virgules entre éléments (aucune après le dernier), les guillemets autour des noms ("nom") et les deux-points.',
    de: 'JSON-Problem: Prüfen Sie Kommas zwischen Elementen (keins nach dem letzten), Anführungszeichen um Namen ("name") und Doppelpunkte.',
    ja: 'JSON の問題です：項目間のカンマ（最後の後には不要）、名前の引用符（"name"）、コロンを確認してください。',
    zh: 'JSON 问题：请检查元素之间的逗号（最后一项后不要加）、名称外的引号（"name"）以及冒号。' },
  { re: /unknown at.rule|unknown property|property .* is not valid|expected closing tag|element is missing end tag|unexpected closing tag|end tag/i,
    en: 'HTML/CSS problem: a tag is not closed correctly, or a property/rule name is misspelled.',
    ar: 'مشكلة في HTML/CSS: وسم لم يُغلق بشكل صحيح، أو اسم خاصية/قاعدة مكتوب بخطأ.',
    fr: "Problème HTML/CSS : une balise n'est pas correctement fermée ou un nom de propriété/règle est mal orthographié.",
    de: 'HTML/CSS-Problem: Ein Tag ist nicht korrekt geschlossen oder ein Eigenschafts-/Regelname ist falsch geschrieben.',
    ja: 'HTML/CSS の問題です：タグが正しく閉じられていないか、プロパティ／ルール名のスペルミスがあります。',
    zh: 'HTML/CSS 问题：标签没有正确闭合，或属性/规则名称拼写错误。' },
  { re: /zerodivisionerror|division by zero|divide by zero/i,
    en: 'You divided by zero, which is impossible. Make sure the divisor is not zero.',
    ar: 'قسمت على صفر وهذا مستحيل. تأكد أن المقسوم عليه ليس صفراً.',
    fr: 'Vous avez divisé par zéro, ce qui est impossible. Vérifiez que le diviseur n\'est pas zéro.',
    de: 'Sie haben durch null geteilt, was unmöglich ist. Stellen Sie sicher, dass der Divisor nicht null ist.',
    ja: 'ゼロで割っています。除数がゼロでないか確認してください。',
    zh: '你除以了零，这是不可能的。请确保除数不为零。' },
  { re: /index ?out ?of ?(range|bounds)|list index|array index|out of range/i,
    en: 'You asked for an item position that does not exist. Counting starts at 0, and the last valid position is length − 1.',
    ar: 'طلبت عنصراً في موضع غير موجود. العدّ يبدأ من 0 وآخر موضع صالح هو الطول − 1.',
    fr: "Vous demandez une position qui n'existe pas. Le comptage commence à 0 et la dernière position valide est longueur − 1.",
    de: 'Sie fragen eine Position ab, die nicht existiert. Die Zählung beginnt bei 0, die letzte gültige Position ist Länge − 1.',
    ja: '存在しない位置の要素を要求しています。数え方は 0 から始まり、最後の有効な位置は 長さ − 1 です。',
    zh: '访问了不存在的位置。计数从 0 开始，最后一个有效位置是 长度 − 1。' }
];

function explain(message, lang) {
  const msg = String(message || '');
  for (const r of RULES) {
    if (r.re.test(msg)) return r[lang] || r.en;
  }
  return undefined;
}

module.exports = { RULES, explain };
